name: ataraxos
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - python=3.11.*
  - gxx=11.4.0
  - cmake=3.27.9
  - pytorch==2.5.1
  - cuda-toolkit=11.8.*
  - cuda-nvcc==11.8.*
  - cuda-runtime==11.8.*
  - pip=23.3.2
  - sysroot_linux-64=2.17
  - msgpack-python=1.1.0
  - pip:
      - einops==0.7.0
      - h5py==3.11.0
      - matplotlib==3.8.2
      - numpy==1.26.2
      - parameterized==0.9.0
      - pyrallis==0.3.1
      - pyyaml==6.0.1
      - scipy==1.11.4
      - submitit==1.5.1
      - tabulate==0.9.0
      - typeguard==4.1.5
      - flask==2.3.3
      - flask-socketio==5.3
      - wandb==0.16.1
      - pre-commit==3.6.0
      - ruff==0.1.11
      - pynvml==12.0.0
